services:
  angular-app:
    build: .
    container_name: stock-front
    restart: always
    ports:
      - "8080:80"
    networks:
      - angular-network

networks:
  angular-network:
    driver: bridge
