services:
  stock-front:
    image: docker.io/sogoredev/stock-front:v3.3.1
    container_name: stock-front
    restart: always
    networks:
      - applications-network

networks:
  applications-network:
    external: true
    name: applications-network
