services:
  stock-front:
    image: sogoredev/stock-front:latest
    container_name: stock-front
    restart: always
    volumes:
      - ./app:/app
    networks:
      - applications-network

networks:
  applications-network:
    external: true
    name: applications-network
