name: Build and Push Frontend Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout cod
      - name: Checkout repository
        uses: actions/checkout@v2

      # Change to the frontend directory
      - name: Navigate to frontend directory
        run: cd frontend

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image
      - name: Build and Push Frontend Image
        run: |
          docker build -t stock-frontend:${{ github.sha }} -f frontend/Dockerfile .
          docker push stock-frontend:${{ github.sha }}
