name: deploy stock front
on: [push]
env:
  IMAGE: stock-front
  VERSION: 0.0.1
jobs:

  create-folder:
    name: create folder
    runs-on: ubuntu-latest
    steps:
      - name: execute commands
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            echo "Creation du dossier sur le serveur.."
            mkdir -p /opt/applications/stock/${{env.IMAGE}}
            echo "Liste des fichiers :"
            ls -al /opt/applications/stock/

  generate-image:
    name: generer une image
    runs-on: ubuntu-latest
    needs: ['create-folder']
    steps:
      - name: cloner le repertoire
        uses: actions/checkout@v3  # Updated checkout action
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: docker.io/sogoredev/stock-front:0.0.1

  run-container:
    name: Générer un container
    runs-on: ubuntu-latest
    needs: [ 'create-folder', 'generate-image' ]
    steps:
      - name: Cloner le répertoire
        uses: actions/checkout@v3
      - name: Vérifier la version de Docker
        run: |
          docker --version
      - name: Installer Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
      - name: Vérifier la version de Docker Compose
        run: |
          docker-compose --version
      - name: Copier le fichier via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          source: "compose.yml"
          target: /opt/applications/stock/${{env.IMAGE}}
      - name: Exécuter les commandes pour démarrer le container
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            set -e
            docker-compose -f /opt/applications/stock/${{env.IMAGE}}/compose.yml up -d

