name: Build and Push Frontend Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # List files to verify the folder structure
      - name: List files in repository
        run: |
          echo "Listing all files in the repository..."
          ls -alh

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and Push Frontend Docker Image
      - name: Build and Push Frontend Image
        run: |
          docker build -t stock-frontend:${{ github.sha }} -f Dockerfile .
          docker push stock-frontend:${{ github.sha }}
