name: Deploy Angular App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t angular-app:latest .

      - name: Login to VPS
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          key: ${{ secrets.DOCKERHUB_TOKEN }}
          script: |
            docker stop angular-app || true
            docker rm angular-app || true
            docker rmi angular-app || true
            mkdir -p ~/angular-app
            rm -rf ~/angular-app/*
      - name: Copy files to VPS
        uses: appleboy/scp-action@v0.1.8
        with:
          source: "./"
          target: "~/angular-app/"
          host: ${{ secrets.HOST }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          key: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Deploy on VPS
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          key: ${{ secrets.DOCKERHUB_TOKEN }}
          script: |
            cd ~/angular-app
            docker-compose down
            docker-compose up -d
